site_name: Jeff.Chen的技术博客

theme:
  name: null
  custom_dir: 'cinder'

# 不要nav，会导致自动菜单目录失效
# nav:
#   - Home: index.md
#   - 关于博主: aboutme.md

# 启动插件，支持markdown调整css
markdown_extensions:
  - attr_list